os: linux
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO_VERSION=2.2
  - DJANGO_VERSION=3.0
  - DJANGO_VERSION=3.1
install:
  - pip install django==$DJANGO_VERSION
  - pip install -r requirements.txt
script:
  - pytest
  - coveralls
  - black --check .
  - isort --check .
  - flake8