# Generated by Django 3.1 on 2020-08-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_oac", "0003_state"),
    ]

    operations = [
        migrations.DeleteModel(name="State",),
        migrations.AlterField(
            model_name="token",
            name="expires_in",
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
