# Generated by Django 3.1 on 2020-08-27 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_oac', '0004_auto_20200827_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='issued',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
