name: test-django-oac

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
        django-version: [2.2, 3.0, 3.1, 3.2, 4.0]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.1
    - name: Install Dependencies
      run: poetry install --no-interaction --no-root
    - name: Install Django ${{ matrix.django-version }}
      run: |
        poetry run pip install django==${{ matrix.django-version }}
    - name: Run Tests
      run: |
        poetry run pytest
